title: Tzeny's demesne
subtitle: Engineering and travelling
description: >- # this means to ignore newlines until "baseurl:"
  A small corner of the internet dedicated to tutorials, resources and galleries created by me

url: "https://tzeny.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About/Contact Me
      url: /about
    - text: Blog
      url: /blog
    - text: Wiki
      url: /wiki
    - text: Galleries
      url: /gallery
    # - text: Shop
    #   url : /shop
    # - text: Contact Me
    #   url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details

author_logo: profile.png
author: Andrei Tenescu
author_bio: |
  The saddle of a bike, the top of a mountain or the cockpit of a kayak are some of the places you might find me on this weekend.

  This world has much to offer, and I am fond of exploring it, either by travelling or reading. I am always on the lookout for parking spaces for my beautiful van/home Rusty.

  This blog presents some of my projects, adventures and mishaps.
author_email: "teny96@gmail.com"
author_location: Romania
author_website_url: "https://tzeny.com"

author_work_experiences:
            - company_name: Mindfully Technologies
              company_logo: xvision.png
              company_url: https://google.com
              designation: CoFounder 
              description: Fullstack developer, jr. data scientist; worked on the artificial intelligence algorithms, backend, testing and CI/CD pipeline
              visibility: true
            - company_name: BitDefender - July 2017 - April 2018
              company_logo: bitdefender.png
              company_url: https://microsoft.com
              designation: Jr. Malware Researcher
              description: Studied malware samples(Windows and Android) to determine functionality and impact; worked on internal Python projects
              visibility: true

author_education_details:
              - college_logo: upt.png
                college_name: Politehnica University of Timișoara
                college_url: https://www.upt.ro/Universitatea-Politehnica-Timisoara_en.html
                college_degree: Master's Degree
                description: Software Engineering - 2019 - 2021 (expected)
                visibility: true
              - college_logo: eeml.png
                college_name: Eastern European Machine Learning Summer School
                college_url: https://www.eeml.eu/
                college_degree: Eastern European Machine Learning Summer School Graduate - 2019
                description: Deep Learning and Reinforcement Learning
                visibility: true
              - college_logo: upt.png
                college_name: Politehnica University of Timișoara
                college_url: https://www.upt.ro/Universitatea-Politehnica-Timisoara_en.html
                college_degree: Bachelor's Degree - 2015 - 2019
                description: Majored in Computer Science
                visibility: true
              - college_logo: coursera.png
                college_name: Coursera
                college_url: https://www.coursera.org/account/accomplishments/certificate/GNYEWLKBYXT9
                college_degree: Stanford Machine Learning MOOC Graduate - 2018
                description: Mathematical fundamentals and use cases of ML(including Neural Networks)
                visibility: true
              - college_logo: intel.png
                college_name: Myriad Labs organized by Intel (Movidius)
                college_url: https://www.movidius.com/
                college_degree: Myriad Labs Graduate - 2018
                description: Computer vision and AI using embedded systems
                visibility: true
              - college_logo: bitdefender.png
                college_name: BitDefender
                college_url: https://www.movidius.com/
                college_degree: "'Code: Analysis, Bugs and Security' Course Graduate - 2017"
                description: Exploits, web vulnerabilities, symbolic execution, fuzzing
                visibility: true

author_project_details:
              - project_thumbnail: xvision_project.jpg
                project_title: XVision
                project_description: Automated X-Ray analysis tool that generates diagnosis and heatmaps (to indicate afflicted areas on the x-ray) using convolutional neural networks
                project_url: https://xvision.app
                visibility: true
              - project_thumbnail: rusty.jpg
                project_title: Rusty
                project_description: Van to campervan conversion that involves everything from 3D modeling and carpentry to electrical engineering and embedded development 
                project_url: https://tzeny.com
                visibility: true

# social links
twitter_username: Tzeny25
github_username:  Tzeny
facebook_username: tenescu.andrei
linkedin_username: tenescu-andrei-0ba631122
# behance_username: johndoe
instagram_username: tzeny15
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
flickr_username: 186474581@N04

future: false
#for comments using disqus
# disqus_shortname: sujay-kundu

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url:

# formspree (contact form)
formspree_email: teny96@gmail.com

# syntax highlighter
markdown: kramdown
kramdown:
   math_engine: mathjax
highlighter: rouge
permalink: :year/:month/:day/:title/

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
# algolia:
#   application_id: D9WA1YKTRQ
#   index_name: blog_posts # You can replace that with whatever name you want
#   files_to_exclude: []
#   nodes_to_index: 'article'
#   search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 9
per_page: 9
paginate_path: "/blog/page/:num/"

# minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
# collections:
#  - products

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      base: Blog
      base_url: /blog
      author: Tzeny
      layout: blog_post
      thumbnail: 2019/12/Sketch.jpg
      categories: 
        - misc
      tags:
        - tag 

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus
  - jekyll-spaceship


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build